version: '3.8'

services:

  shorten-service:
    container_name: shorten-service
    build:
      context: ./url-shortner-service  # Path to your shorten-service Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - SERVER_ADDRESS=0.0.0.0
      - GRPC_SERVER_PORT=9090
      - GRPC_SERVER_ADDRESS=0.0.0.0
    networks:
      - url-network

  redirect-service:
    container_name: redirect-service
    build:
      context: ./url-redirect-service  # Path to your redirect-service Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
      - SERVER_ADDRESS=0.0.0.0
      - grpc.client.urlShortener.address=static://shorten-service:9090
    depends_on:
      - shorten-service
    networks:
      - url-network

  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway  # Path to your api-gateway Dockerfile
    ports:
      - "8082:8082"
    environment:
      - SERVER_PORT=8082
      - SERVER_ADDRESS=0.0.0.0
    depends_on:
      - shorten-service
      - redirect-service
    networks:
      - url-network

networks:
  url-network:
    driver: bridge
