server:
  port: 8082

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        # Forward /api/create to Shorten Service (8080)
        - id: shorten-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/create

        # Forward /{shortCode} to Redirect Service (8081)
        - id: redirect-service
          uri: http://localhost:8081
          predicates:
            - Path=/{shortCode}
